### ISSUE TITLE
Add search feature under Clubs

### ISSUE THREAD

**Issue by Chiuterence** [AndrewManHayChiu/court#32]
Add feature to search a club location

**Comment by AndrewManHayChiu** [comment]
This is a good one.

In fact, I'm going to need a way to filter or suggest clubs/socials that are relevant for a user.

For example, if a user is registered in Hong Kong, they are not being given Australian clubs by default.

This is a small issue for now, but if there are many users then this will become a higher priority.

**Comment by AndrewManHayChiu** [comment]
I've added a Search bar in the Clubs page.

I'll look at putting in a filter option along each Column.
