### ISSUE TITLE
Suggestions for "Club" details

### ISSUE THREAD

**Issue by Chiuterence** [AndrewManHayChiu/court#47]
- [x] Insert option for "Irregular" under "Day"
- [x] For "Time", and under minute, just do "00/15/30" to keep things simple
- [x] "Price" should not be an entry in the "Club" details, as a club can organise sessions with difference prices. If a club wants to indicate the average or normal price, it should be included in notes to the club somewhere. Instead, "Price" should be assigned to each session that is created. Also need a currency for this
- [x] In the Clubs list, under the column "RSVP Required", instead of true/false, do yes/no
- [x] In the Clubs list, add a new column for "orgniser", or do "name/organiser" (in HK, organisers don't have a club name, just the organiser)

Just also thinking about the club/session details - In HK, an organiser/club may not have a regular location - in which case, the club may not have a designated location and the session details will need to be able to select the location. e.g. Club one can hold a session at Stadium A on one day, and then a session ad Stadium B on another day

**Comment by AndrewManHayChiu** [comment]
All suggestions done.
